[
  "noanim, .*"
  "xray 1, .*"

  "noanim, noanim"
  "blur, noanim"
  "blur, gtk-layer-shell"
  "ignorezero, gtk-layer-shell"
  "blur, launcher"
  "ignorealpha 0.3, launcher"
  "blur, notifications"
  "ignorealpha 0.3, notifications"

  # ags
  "blur, bar"
  "ignorealpha 0.3, bar"
  "blur, corner.*"
  "ignorealpha 0.3, corner.*"
  "blur, indicator.*"
  "ignorealpha 0.3, indicator.*"
  "blur, overview"
  "ignorealpha 0.3, overview"
  "xray 0, overview"
  "blur, cheatsheet"
  "ignorealpha 0.3, cheatsheet"
  "blur, sideright"
  "ignorealpha 0.3, sideright"
  "blur, sideleft"
  "ignorealpha 0.3, sideleft"
  "blur, indicatorundefined"
  "ignorealpha 0.3, indicatorundefined"
  "blur, osk"
  "ignorealpha 0.3, osk"
  "blur, session"
]
