[
  "noanim, .*"
  "xray 1, .*"

  "noanim, noanim"
  "blur, noanim"
  "blur, gtk-layer-shell"
  "ignorezero, gtk-layer-shell"
  "blur, launcher"
  "ignorealpha 0.5, launcher"
  "blur, notifications"
  "ignorealpha 0.69, notifications"

  # ags
  "blur, bar"
  "ignorealpha 0.64, bar"
  "blur, corner.*"
  "ignorealpha 0.69, corner.*"
  "blur, indicator.*"
  "ignorealpha 0.69, indicator.*"
  "blur, overview"
  "ignorealpha 0.69, overview"
  "blur, cheatsheet"
  "ignorealpha 0.69, cheatsheet"
  "blur, sideright"
  "ignorealpha 0.69, sideright"
  "blur, sideleft"
  "ignorealpha 0.69, sideleft"
  "blur, indicatorundefined"
  "ignorealpha 0.69, indicatorundefined"
  "blur, osk"
  "ignorealpha 0.69, osk"
  "blur, session"
]
