maximized = false
srgb = true

[font]
normal = ["FiraCode Nerd Font"]
size = 13
edging = "subpixelantialias"

[font.features]
"FiraCode Nerd Font" = [
  "+zero",
  "+onum",
  "+ss04",
  "+cv19",
  "+cv23",
  "+ss09",
  "+ss06",
  "+ss07",
  "+ss10",
]
