[
  "SUPER,Q,killactive"
  "SUPER,T,exec,kitty"
  "SUPER,C,togglespecialworkspace,calc"
  "SUPER_SHIFT,C,exec,hyprpicker"
  "SUPER_SHIFT,V,exec,slurp | grim -g - - | wl-copy"
  "SUPER,P,togglefloating,"
  "SUPER,P,pin,"
  "SUPER,D,fullscreen,1"
  "SUPER,D,movetoworkspace,empty"
  "SUPER,V,fullscreen,0"
  "SUPER,V,movetoworkspace,empty"

  "SUPER_SHIFT,up,movewindow,u"
  "SUPER_SHIFT,down,movewindow,d"
  "SUPER_SHIFT,left,movewindow,l"
  "SUPER_SHIFT,right,movewindow,r"

  "SUPER_SHIFT,S,movetoworkspace,special:terminal"
  "SUPER,S,togglespecialworkspace,terminal"

  "SUPER,up,movefocus,u"
  "SUPER,down,movefocus,d"
  "SUPER,left,movefocus,l"
  "SUPER,right,movefocus,r"

  "SUPER,f,workspace,r-1"
  "SUPER,h,workspace,r+1"
  "SUPER_SHIFT,f,movetoworkspace,r-1"
  "SUPER_SHIFT,h,movetoworkspace,r+1"
  "SUPER,mouse_up,workspace,r+1"
  "SUPER,mouse_down,workspace,r-1"

  # just dump the window anywhere
  "SUPER,x,movetoworkspacesilent,empty"

  "SUPER,1,workspace,1"
  "SUPER,2,workspace,2"
  "SUPER,3,workspace,3"
  "SUPER,4,workspace,4"
  "SUPER,5,workspace,5"
  "SUPER,6,workspace,6"
  "SUPER,7,workspace,7"
  "SUPER,8,workspace,8"
  "SUPER,9,workspace,9"

  "SUPER_SHIFT,1,movetoworkspace,1"
  "SUPER_SHIFT,2,movetoworkspace,2"
  "SUPER_SHIFT,3,movetoworkspace,3"
  "SUPER_SHIFT,4,movetoworkspace,4"
  "SUPER_SHIFT,5,movetoworkspace,5"
  "SUPER_SHIFT,6,movetoworkspace,6"
  "SUPER_SHIFT,7,movetoworkspace,7"
  "SUPER_SHIFT,8,movetoworkspace,8"
  "SUPER_SHIFT,9,movetoworkspace,9"
]
